AndyGrant/OpenBench

Client/Client.py
OpenBench/models.py
OpenBench/utils.py
Templates/OpenBench/newTest.html
Templates/OpenBench/test.html

This PR implements support for network files (for NNUE based engines) in OpenBench:
- Test model object is modified and it contains two new fields: devnetwork and basenetwork (256 characters max)
- Client script is modified to download devnetwork and basenetwork into 'Engines' directory and pass as option.EvalFile to an engine
- In case Engines folder already contains eval file the download is skipped to preserve bandwidth
- UI is modified to allow net URLs to be passed during creation of a test
- UI is modified to view net URLs to per each test
This is how UI looks like now
Creation of new test:
Seeing existing test without devnetwork and basenetwork parameters:
Seeing existing test with devnetwork and basenetwork parameters:
This PR is tested on my local open bench instance …

Implement net files support for NNUE engines

---

OpenBench/utils.py

This PR implements enforcement of HTTPS to be used for network files.
Testing scenarios:
1. Passing network file on a HTTP link results in error
2. Passing network file on a HTTPS link works well
3. Empy network file links are still allowed

Enforce HTTPS urls for network files

---

Client/Client.py

This PR implements proper time scaling for NNUE based engines in OpenBench by using network file during 'bench' command:
- Before performing 'bench' command the OB client downloads the appropriate network file for dev/base engine
- Network file is passed to command line only if configured, so no need to update existing engines that do not support option.EvalFile in the command line
- The exact format of the command line becomes: _engine bench option.EvalFile=path_to_network_file_
Testing scenarios:
1. Passing network file to the test (in this case 'option.EvalFile' is added to bench command line)
2. Not passing network file to the test (in this case original command line is used that only does 'bench')

Use network file during bench for proper time scaling

---

Client/Client.py

This PR just adds a new field to the CUSTOM_SETTINGS variable indicating if the engine supports multiprocessed build, and uses the given '--threads' argument when running the Client as the number of threads used for building (with the flag -j). If the engine doesn't support it, no additional flag is given to the 'make' command.

Make the Client use multiprocessed 'make' commands for engines that support it

---

Client/Client.py

Fall back to OPENBENCH_USERNAME and OPENBENCH_PASSWORD environment
variables when username/password are not passed as command line
arguments. Passing credentials in command line is problematic in
multiuser machines, as full command lines may be visible in process
listings.
***
**The background for this:** I'm setting up a Docker container for OpenBench client + compilers etc. This is mainly for myself, but I'm probably going to publish it in Docker hub. In case someone wants to run the Docker container in cloud or similar, I'd like to avoid revealing the username/password in process listings (e.g., ps -ef / htop / etc).
Also, I don't claim to be a fluent Python dev. Feel free to point out how this should have been done differently :)

Use credentials from environment when not supplied in command line

---

OpenBench/config.py

This change reduces Igel default testing bounds to [0.00, 3.00].

reduce igel testing bounds

---

OpenBench/config.py

* Added `UHO_XXL_+0.90_+1.19` book as `Pohl.pgn.zip`
* Added configuration for https://github.com/kz04px/4ku. This is a temporary project, only to be included in OB until the TCEC 4k tournament: https://wiki.chessdom.org/TCEC_4k_Rules

Add 4ku engine and Pohl.pgn

---

Client/Client.py

In the function server_configure_worker(), if the error appears in the response is "Bad Machine Id" then delete machine.txt before exiting.

Delete machine.txt if error "Bad Machine Id" is thrown

---

Client/Client.py
Engines/4ku.json
Engines/Berserk.json
Engines/Bit-Genie.json
Engines/BlackMarlin.json
Engines/Demolito.json
Engines/Drofa.json
Engines/Ethereal.json
Engines/FabChess.json
Engines/Halogen.json
Engines/Igel.json
Engines/Koivisto.json
Engines/Laser.json
Engines/RubiChess.json
Engines/Seer.json
Engines/Stash.json
Engines/Weiss.json
Engines/Winter.json
Engines/Zahak.json
OpenBench/config.py
OpenBench/management/commands/runserver.py
OpenBench/models.py
OpenBench/utils.py
OpenBench/views.py
Templates/OpenBench/create_test.html
Templates/OpenBench/machine.html
Templates/OpenBench/test.html

Resolves https://github.com/AndyGrant/OpenBench/issues/139
Resolves https://github.com/AndyGrant/OpenBench/issues/138
Resolves https://github.com/AndyGrant/OpenBench/issues/137
Resolves https://github.com/AndyGrant/OpenBench/issues/136
Resolves https://github.com/AndyGrant/OpenBench/issues/135
Resolves https://github.com/AndyGrant/OpenBench/issues/133
Resolves https://github.com/AndyGrant/OpenBench/issues/121
* Small CSS fixes to the test page view
* Massive cleanup for Client.py to remove globals due to Windows env. issues
* Retrigger workflow runs if they are expired, or appear to be bugged but are fine
* Collapse all results into a single object for a given machine once again
* Full fledged support for artifact selection for various vector instr. sets
* Allow specific TB for either …

Collection of massive breaking changes

---

Client/Client.py
OpenBench/config.py
OpenBench/utils.py

Collects results as game-pairs, instead of as individual results. This removes some noise and bias that may have existed prior.
The master thread now handles all reporting to the OpenBench server. Help threads, ( one for each --nsockets or -N ), will place their results in a `multiprocessing.Queue()`. 
We will report `report_rate`-pairs at a time. However we will only report up to once every 30 seconds. This means we might batch report many many games at a time. This acts as a natural remedy to if someone were to have created an insanely short time control, or low nodes test. This will cause fixed-game tests to go over the cap. IE, a 40,000 game test is very likely to receive a small number of games above 40,000. Fixing these seems non-trivial, and also not important. 
The Client also …

Client Reporting

---

Client/Client.py
OpenBench/static/style.css
OpenBench/views.py
Templates/OpenBench/errors.html
Templates/OpenBench/machines.html

Upon completion of the workload, parse all newly created PGN files for errors. We identify these by the Termination header. Any errors found are reported to the server.
Modify the PGN naming scheme to be more versatile; Name them as ``<test-id>.<result-id>.<cutechess-seed>.pgn``. This makes it more easy to identify PGNs and their association with tests, if someone were to look at the raw files.
Commit some code, partially based on Kimmy's efforts, which will help process PGNs without the use of python-chess' PGN libs, which are far too slow.
Cleanup some interfaces which had far too much information on them
Delete some very ancient auto-approving code that only applied to the cross-approval case. Frankly no one is running OpenBench instances with cross-approval. 
Display both the base and …

Report all errors after workload is finished

---

OpenBench/static/copy_text.js
OpenBench/templatetags/mytags.py
OpenBench/workloads/create_workload.py
Templates/OpenBench/test.html
Templates/OpenBench/tune.html

* Move the copy_text function to /static
* Record the original order of inputs for SPSA
* Display SPSA data in the original order ( if it exists )
* Format ints as ints instead of floats for Start/Min/Max
* Swap the Curr/Start column to clearly show the initial triplet
* Right align all of the SPSA stuff
* Change the copy button on Tunes to be the original SPSA Input

Some improvements to CSS/HTML/JS

---

Client/Client.py
OpenBench/templatetags/mytags.py

On some (all?) systems, VNNI is reported as `avx512vnni`, and there supposedly can be inconsistency between the reported names of extensions. This will require removal of dots and underscores from engine configs that list those extensions (`SSE4_1`, `SSE4_2`, `AVX512_VNNI`).

Strip dots and underscores from ISA extension names

---

Client/pgn_util.py
Client/worker.py
Config/config.json
Engines/Torch.json
OpenBench/config.py
OpenBench/models.py
OpenBench/templatetags/mytags.py
OpenBench/urls.py
OpenBench/views.py
OpenBench/workloads/create_workload.py
OpenBench/workloads/get_workload.py
OpenBench/workloads/verify_workload.py
Templates/OpenBench/create_workload.html
Templates/OpenBench/test.html

Creates a new option on tests for PGN uploading. The options are...
1. False -- Don't upload
2. Verbose -- Upload without all comment data, ie {eval depth/seldepth time-ms nodes}
3. Compact -- Upload with minimal comment data, ie {eval}
PGNs are stripped heavily, to a mostly-legal format, which includes all needed headers. The only known illegality in the PGN is that the movelist spans greater than 255 characters, which is mentioned as being illegal in the specification. The removal of the movenumbers is perfectly legal. 
The API is not included in this commit for downloading the PGNs.

Allow uploading PGNs to the server for tests

---

OpenBench/static/style.css
OpenBench/views.py
Templates/OpenBench/index.html

Adds headers to the active tests view indicating the priority level of the tests below it.
In `master`, this information is somewhat hinted at by the order in which tests are displayed, but it is difficult to determine, for example, which tests are making progress. With this patch, this can be determined at a glance.

Add priority group headings

---

Client/client.py
Client/worker.py
Config/config.json
OpenBench/workloads/get_workload.py

Refer to https://github.com/AndyGrant/OpenBench/wiki/Workload-Assignment for a full understanding of the algorithm. 
OpenBench/workloads/get_workload:select_workload() implements this logic step-by-step as indicated on the Wiki. 
These changes introduce a breaking change to client.py, which was supposed to never be done. This was needed, as adding any additional arguments will trigger the ArgParser to error out. This is resolved with the following structure, which could have been implemented initially, with greater forethought.
```python
args, unknown = p.parse_known_args()
```
I did also note that line 146 in client.py will break for forks of OpenBench with name changes. IE @TheBlackPlague's OpenBench fork, although that one is so far master behind it is not an issue at the moment.

Allow for --focus ENGINE1 [ENGINE2 ....] to prioritize Workload Assignments

---

Client/utils.py
Client/worker.py

The output binary is saved alongside the makefile initially, and moved after the fact. This was done to account for Windows and cross-drive issues due to temp filesystems. Because we are saving alongside the makefile, we can just use a relative path, ie the basename of the engine binary, to avoid possible issues in some engine build scripts.
Also, check process exitcode instead of just checking for the binary when building 
Also, pretty-print the compiler error, even though it is sent to the server

Fixes for relative vs absolute file paths when building

---

OpenBench/static/style.css

On smaller screens, a title with non-breaking whitespaces overflows, breaking the layout. This PR adjusts the font size to the screen width to avoid it.

Adaptive title font size

---

Client/worker.py
OpenBench/utils.py

Turn some strings to raw strings to fix errors raised by the Python 3.12 interpreter on invalid escape sequences.

Fix invalid escape sequences in pattern strings

---

OpenBench/views.py

The input fields for engine repos on the profile page aren't read-only, giving the impression that repo links can be changed.
This PR implements the ability to change them. Otherwise, adding the `readonly` attributes would be nice.

Implement editing of profile repos

---

Templates/OpenBench/workload.html

Disable the restart button for finished tests that have been completed (either passed or failed), as continuing a completed test doesn't seem like the intended behavior.

Disable restart button for completed tests

---

Templates/OpenBench/network.html
Templates/OpenBench/uploadnet.html

This PR adds missing `for` attributes to associate labels with input controls.

Add missing for attributes on some html forms

---

OpenBench/static/form.css

The textarea form controls have a focus style applied by default, particularly for the SPSA input field. This PR adds the missing focus modifier.

Add missing focus modifier for textarea

---

Engines/Halogen.json

- Add clang++ as supported compiler
- Add compiler version ranges
- Change default book to UHO_4060_v2
- Add OutputLevel=Minimal uci option

Adjust Halogen configuration

---

OpenBench/stats.py
OpenBench/templatetags/mytags.py

fix misspelling in "pentanomial" syllable abbreviation.
Pntml = pe-n-tano-mi-al ❌ 
Ptnml = pen-ta-no-mi-al ✅

Fix syllable abbreviation

---

OpenBench/models.py

This fixes test editions from the admin page, which would previously error out if any of the network/genfens fields was left empty.

Allow some fields in the test model to be left empty

---

Engines/Torch.json

Not sure I did that correctly.
Use soft nodes when doing 57.5 node tests for datagen.

Use soft nodes when doing fixed node tests for datagen.

---

requirements.txt

scipy 1.9.0 is the lowest version that allows you to call `scipy.optimize.brentq`, which is required in [`OpenBench/stats.py`](https://github.com/AndyGrant/OpenBench/blob/8216eec36d4eb2a40f72788c130843475da79fbd/OpenBench/stats.py#L117)
Context:
When attempting to set up an OpenBench server on a machine that had an outdated version of scipy (`1.7.3`), I encountered errors whenever clients would try to upload test results to the server.
After debugging, it was discovered that the scipy version was too old, and needed to be updated.
Evidence:
```
$ pip3 freeze | grep scipy
scipy==1.9.0
$ python3
Python 3.10.15 (main, Oct  3 2024, 07:27:34) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
>>> print (scipy.optimize.brentq)
<function …
```

fix: add `scipy==1.9.0` to server's `requirements.txt`

---

OpenBench/stats.py
requirements.txt

versions long before 1.9.0 still has optimize, the problem is it needs to be imported seperately https://github.com/numenta/htmresearch/pull/704
this is the specific scipy commit https://github.com/scipy/scipy/pull/15230

remove scipy version requirement

---

OpenBench/workloads/create_workload.py

Updated the paths in `create_workload()` when a workload creation causes an error.
Didn't see any other instances of `newTest`, `newTune`, or `newDatagen` that needed to be changed.

fix: updated paths in create_workload.py

---

Client/bench.py
Client/client.py
Client/genfens.py
Client/pgn_util.py
Client/utils.py
Client/worker.py
Config/config.json

TLDR: reloading worker is not sufficient, as the modules loaded by worker will not also be reloaded. Resolving this is non-trivial, mostly due to the nature of `from x import ...` statements, which would require explicit reloading of each loaded entity. Swapping the entire client to use `import x` means it should be possible to reload just the list of python modules, at the top of the worker.
This has not bricked Torchbench or noob workers on grantnet, but it did brick Terje's worker. The process of updating to this version might get bricked, but the hope is that after this, its fine.

Attempt to resolve cascading reimports on worker updates

---

Engines/Stash.json

Change the default book to be used from v37 onwards, and add some presets for non-regression tests as well as tunes.
Also change the default parameters for datagen runs, and remove POPCNT from the cpuflags config as it is not strictly required for building Stash.

Update Stash config

---

Templates/OpenBench/base.html

Safari on mobile automatically formats Unix time stamp to links to phone numbers. E.g. `1746223790` to `<a href="tel:1746223790">1746223790</a>`. Since `innerHTML` returns the entire HTML content contained within the element, this breaks the date calculation code. Using `textContent`, which ignores html tags, fixes this issue.

Fix safari date display on mobile
